-- Exception localization
INSERT INTO placeholder_texts(code, lang, text) VALUES
    -- GENERAL
    ('error.ready', 'en', 'Character must be ready to perform this action.'),
    ('error.ready', 'cs', 'Postava musí být v připraveném stavu na provedení této akce.'),
    ('error.premium', 'en', 'You must have a premium account to use this feature.'),
    ('error.premium', 'cs', 'Potřebuješ premium účet na použití této funkce.'),
    -- RESOURCES
    ('error.no-resources', 'en', 'You do not have enough resources to perform this action.'),
    ('error.no-resources', 'cs', 'Nemáš dostatek surovin na provedení této akce.'),
    ('error.no-food', 'en', 'You do not have enough food to perform this action.'),
    ('error.no-food', 'cs', 'Nemáš dostatek jídla na provedení této akce.'),
    ('error.no-junk', 'en', 'You do not have enough junk to perform this action.'),
    ('error.no-junk', 'cs', 'Nemáš dostatek šrotu na provedení této akce.'),
    ('error.no-caps', 'en', 'You do not have enough caps to perform this action.'),
    ('error.no-caps', 'cs', 'Nemáš dostatek zátek na provedení této akce.'),
    ('error.no-fame', 'en', 'You do not have enough fame to perform this action.'),
    ('error.no-fame', 'cs', 'Nemáš dostatek slávy na provedení této akce.'),
    ('error.no-information', 'en', 'You do not have enough information to perform this action.'),
    ('error.no-information', 'cs', 'Nemáš dostatek informací na provedení této akce.'),
    ('error.no-information-level', 'en', 'You need higher information level to perform this action.'),
    ('error.no-information-level', 'cs', 'Potřebuješ vyšší uroveň informací na provedení této akce.'),
    ('error.no-influence', 'en', 'You do not have enough influence to perform this action.'),
    ('error.no-influence', 'cs', 'Nemáš dostatek vlivu na provedení této akce.'),
    -- TRADE
    ('error.trade-no-resources', 'en', 'You did not specify any resources to be traded.'),
    ('error.trade-no-resources', 'cs', 'Nezvolil jsi žádné suroviny k obchodu.'),
    ('error.trade-resource-limit', 'en', 'Your character cannot carry that many resources..'),
    ('error.trade-resource-limit', 'cs', 'Tvá postava neunese tolik surovin.'),
    ('error.trade-limit', 'en', 'You exceeded the limit of trades with the same clan during single turn. Try purchasing item from some other clan.'),
    ('error.trade-limit', 'cs', 'Překročil jsi limit množství obchodů s konkrétním klanem v rámci jednoho kola. Zkus koupit předmět od někoho jiného.'),
    ('error.trade-invalid-price', 'en', 'Specified price must be between the market price and double the market price.'),
    ('error.trade-invalid-price', 'cs', 'Stanovená cena se musí pohybovat mezi tržní hodnotou předmětu a jejím dvojnásobkem.'),
    -- ITEMS
    ('error.item-equip', 'en', 'Your character has already equipped an item of this type.'),
    ('error.item-equip', 'cs', 'Tvá postava už má jeden předmět tohoto typu. Nejprve ji musíš původní předmět odebrat.'),
    ('error.item-intellect', 'en', 'Your character has low intellect to use an item of this type.'),
    ('error.item-intellect', 'cs', 'Tvá postava má příliš nízký intelekt na použití tohoto předmětu.'),
    ('error.item-max-stat', 'en', 'Your character is either injured or has already reached the maximum level of this stat.'),
    ('error.item-max-stat', 'cs', 'Tvá postava je zraněna nebo již dosáhla maximální úrovně této vlastnosti.'),
    -- FACTIONS
    ('error.combat-limit', 'en', 'Only one attack action per turn is permitted!'),
    ('error.combat-limit', 'cs', 'Je povolen pouze jeden útok na cizí klan za kolo!'),
    -- ARENA
    ('error.arena-limit', 'en', 'Only one character in arena per turn is permitted!'),
    ('error.arena-limit', 'cs', 'Je povolen pouze jeden vstup do arény za kolo!'),
    ('error.arena-ranged', 'en', 'Ranged weapon are not permitted in the arena!'),
    ('error.arena-ranged', 'cs', 'Střelné zbraně nejsou v aréně povoleny!'),
    -- TAVERN
    ('error.tavern-limit', 'en', 'You cannot exceed your population limit!'),
    ('error.tavern-limit', 'cs', 'Nemůžeš překročit svůj populační limit!'),
    -- CONSTRAINTS
    ('error.constraint-health', 'en', 'Character must be healthy to perform this action!'),
    ('error.constraint-health', 'cs', 'Postava musí být zdravá, aby mohla vykonat tuto akci!'),
    ('error.constraint-item', 'en', 'Character must carry an item to perform this action!'),
    ('error.constraint-item', 'cs', 'Postava musí nést předmět, aby mohla vykonat tuto akci!'),
    ('error.constraint-weapon', 'en', 'Character must carry a weapon to perform this action!'),
    ('error.constraint-weapon', 'cs', 'Postava musí nést zbraň, aby mohla vykonat tuto akci!'),
    ('error.constraint-gear', 'en', 'Character must carry a gear to perform this action!'),
    ('error.constraint-gear', 'cs', 'Postava musí nést výbavu, aby mohla vykonat tuto akci!'),
    ('error.constraint-outfit', 'en', 'Character must have an outfit to perform this action!'),
    ('error.constraint-outfit', 'cs', 'Postava musí mít zbroj, aby mohla vykonat tuto akci!'),
    ('error.constraint-male', 'en', 'Character must be male to perform this action!'),
    ('error.constraint-male', 'cs', 'Postava musí být muž, aby mohla vykonat tuto akci!'),
    ('error.constraint-female', 'en', 'Character must be female to perform this action!'),
    ('error.constraint-female', 'cs', 'Postava musí být žena, aby mohla vykonat tuto akci!');