-- First turn
INSERT INTO turns (turn_id) VALUES
    (1);

-- Location descriptions
INSERT INTO location_descriptions(location, scouting, food_bonus, junk_bonus, information_bonus, encounter_chance, item_chance, description, info, image_url) VALUES
    ('NEIGHBORHOOD', false, 0, 0, 0, 0, 0, 'locations.neighborhood.description', 'locations.neighborhood.info',
    'https://storage.googleapis.com/withergate-images/locations/neighborhood.png'),
    ('WASTELAND', true, 1, 1, 0, 25, 10, 'locations.wasteland.description', 'locations.wasteland.info',
    'https://storage.googleapis.com/withergate-images/locations/wasteland.png'),
    ('CITY_CENTER', true, 2, 2, 2, 40, 20, 'locations.citycenter.description', 'locations.citycenter.info',
    'https://storage.googleapis.com/withergate-images/locations/city.png');

INSERT INTO localized_texts(location_name, lang, text) VALUES
    ('NEIGHBORHOOD', 'en', 'Neighborhood'),
    ('NEIGHBORHOOD', 'cs', 'Sousedství'),
    ('WASTELAND', 'en', 'Wasteland'),
    ('WASTELAND', 'cs', 'Pustina'),
    ('CITY_CENTER', 'en', 'City center'),
    ('CITY_CENTER', 'cs', 'Centrum města');

INSERT INTO localized_texts(location_description, lang, text) VALUES
    ('NEIGHBORHOOD', 'en', 'Neighborhood is the area around your camp. It is a relatively safe place since you have been living there for quite some time. It is a safe location to search for junk and food. Do not expect to find anything too valuable, though.'),
    ('NEIGHBORHOOD', 'cs', 'Sousedství je území v okolí tvého kempu. Je to relativně klidné místo, už tady přeci jen chvíli žijete. Ideální kratochvílí v této oblasti je sbírání jídla a šrotu. Nečekejte, že tady narazíte na nějaké zázraky.'),
    ('WASTELAND', 'en', 'Wasteland is the desolated area all around you. It might seem abandonded but do not be mistaken. Other characters roam this area so searching this place can sometimes be dangerous.'),
    ('WASTELAND', 'cs', 'Pustina je vyprahlá oblast všude okolo. Může se zdát opuštěná, ale věz, že se zde nachází mnoho nebezpečí.'),
    ('CITY_CENTER', 'en', 'The ruins of the center of Withergate hides the most valuable treasures. Unfortunately, run by local gangs and roamed by scavengers, this place can sometimes prove to be very dangerous. On the other hand, if you are lucky, you can find some useful items here.'),
    ('CITY_CENTER', 'cs', 'Ruiny centra Withergate ukrývají ty největší poklady. Jedná se o velmi nebezpečnou oblast obývanou lokálními gangy, mutanty a tím nejhorším, co pustina vyplivla. Pokud budete mít štěstí, můžete zde nalézt opravdové poklady.');

INSERT INTO localized_texts(location_info, lang, text) VALUES
    ('NEIGHBORHOOD', 'en', 'Neighborhood is a relatively safe location. The most probable outcome is finding some junk or food.'),
    ('NEIGHBORHOOD', 'cs', 'Sousedství je relativně klidná oblast. Nejpravděpodobnější výsledek průzkumu bude jídlo a šrot.'),
    ('WASTELAND', 'en', 'Wasteland has an increased chance for encountering some potentially dangerous events. However, handling such event well might lead to an interesting reward.'),
    ('WASTELAND', 'cs', 'V pustině je vyšší šance na nebezpečné události. Na druhou stranu, při úspěchu je zde také šance na vyšší odměnu. Je možné zde zjistit zajímavé informace.'),
    ('CITY_CENTER', 'en', 'City has the highest risk of encoutering dangerous events. On the other hand, it also provides higher chances for finding valuable loot.'),
    ('CITY_CENTER', 'cs', 'Centrum města má nejvyšší riziko na nebezpečné události. Pokud se vám podaří přežít, tak je zde ale i šance na vysoké odměny. Také se zde postavy mohou dozvědět hodně zajímavých informací při pátrání.');

-- Random names
INSERT INTO name_prefixes (value) VALUES
    ('Acid'),
    ('Addicted'),
    ('Annoying'),
    ('Beefy'),
    ('Big'),
    ('Black'),
    ('Bold'),
    ('Captain'),
    ('Charming'),
    ('Clever'),
    ('Cold'),
    ('Crooked'),
    ('Dancing'),
    ('Daring'),
    ('Desperate'),
    ('Dreadful'),
    ('Edgy'),
    ('Faithful'),
    ('Fearless'),
    ('Fierce'),
    ('Foxy'),
    ('General'),
    ('Good'),
    ('Groovy'),
    ('Hateful'),
    ('Hipster'),
    ('Hungry'),
    ('Hysterical'),
    ('Laughing'),
    ('Lieutenant'),
    ('Lonely'),
    ('Long'),
    ('Loud'),
    ('Lunatic'),
    ('Lusty'),
    ('Mad'),
    ('Manic'),
    ('Mean'),
    ('Mesmerizing'),
    ('Misty'),
    ('Moody'),
    ('Moon'),
    ('Nasty'),
    ('Old'),
    ('Plastic'),
    ('Puzzled'),
    ('Quick'),
    ('Rotting'),
    ('Salty'),
    ('Sarcastic'),
    ('Sharp'),
    ('Silent'),
    ('Skinny'),
    ('Small'),
    ('Smelly'),
    ('Space'),
    ('Speedy'),
    ('Spiteful'),
    ('Spotty'),
    ('Stoic'),
    ('Strong'),
    ('Thirsty'),
    ('Tormented'),
    ('Troubled'),
    ('Vengeful'),
    ('Witty'),
    ('Young'),
    ('Zealous');

INSERT INTO names (gender, value) VALUES
    ('FEMALE', 'Angie'),
    ('FEMALE', 'Carol'),
    ('FEMALE', 'Chance'),
    ('FEMALE', 'Corona'),
    ('FEMALE', 'Ember'),
    ('FEMALE', 'Enigma'),
    ('FEMALE', 'Faythe'),
    ('FEMALE', 'Flower'),
    ('FEMALE', 'Fox'),
    ('FEMALE', 'Garona'),
    ('FEMALE', 'Grace'),
    ('FEMALE', 'Greta'),
    ('FEMALE', 'Honey'),
    ('FEMALE', 'Jill'),
    ('FEMALE', 'Julia'),
    ('FEMALE', 'Kara'),
    ('FEMALE', 'Kathy'),
    ('FEMALE', 'Lizzy'),
    ('FEMALE', 'Mirela'),
    ('FEMALE', 'Misty'),
    ('FEMALE', 'Moon'),
    ('FEMALE', 'Muse'),
    ('FEMALE', 'Nemo'),
    ('FEMALE', 'Pepper'),
    ('FEMALE', 'Piper'),
    ('FEMALE', 'Pippy'),
    ('FEMALE', 'Pixy'),
    ('FEMALE', 'Rascal'),
    ('FEMALE', 'Rey'),
    ('FEMALE', 'Rika'),
    ('FEMALE', 'Rita'),
    ('FEMALE', 'Snow-white'),
    ('FEMALE', 'Sunshine'),
    ('FEMALE', 'Suzy'),
    ('FEMALE', 'Tamara'),
    ('FEMALE', 'Tara'),
    ('FEMALE', 'Toots'),
    ('FEMALE', 'Vyolet'),
    ('FEMALE', 'Witch'),
    ('FEMALE', 'Yara'),
    ('MALE', 'Arnold'),
    ('MALE', 'Atlas'),
    ('MALE', 'Bob'),
    ('MALE', 'Bruiser'),
    ('MALE', 'Butch'),
    ('MALE', 'Cypher'),
    ('MALE', 'Dan'),
    ('MALE', 'Dash'),
    ('MALE', 'Dexter'),
    ('MALE', 'Ekko'),
    ('MALE', 'Exo'),
    ('MALE', 'Fiddles'),
    ('MALE', 'Frank'),
    ('MALE', 'Grub'),
    ('MALE', 'Hog'),
    ('MALE', 'Hugo'),
    ('MALE', 'Igor'),
    ('MALE', 'James'),
    ('MALE', 'Joe'),
    ('MALE', 'John'),
    ('MALE', 'Kevin'),
    ('MALE', 'Luke'),
    ('MALE', 'Martin'),
    ('MALE', 'Neville'),
    ('MALE', 'Patch'),
    ('MALE', 'Patches'),
    ('MALE', 'Paul'),
    ('MALE', 'Petee'),
    ('MALE', 'Ragnar'),
    ('MALE', 'Ron'),
    ('MALE', 'Rufus'),
    ('MALE', 'Sam'),
    ('MALE', 'Simon'),
    ('MALE', 'Smuggy'),
    ('MALE', 'Spot'),
    ('MALE', 'Tom'),
    ('MALE', 'Tycho'),
    ('MALE', 'Viper'),
    ('MALE', 'Walter'),
    ('MALE', 'Weeds'),
    ('MALE', 'Worm'),
    ('MALE', 'Xaver'),
    ('MALE', 'Zack'),
    ('MALE', 'Zafod'),
    ('MALE', 'Zero'),
    ('MALE', 'Nick');

INSERT INTO avatars (gender, image_url) VALUES
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male01.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male02.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male03.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male04.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male05.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male06.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male07.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male08.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male09.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male10.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male11.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male12.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male13.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male14.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male15.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male16.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male17.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male18.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male19.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male20.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male21.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male22.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male23.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male24.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male24.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male25.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male26.png'),
    ('MALE', 'https://storage.googleapis.com/withergate-images/avatars/male27.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female01.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female02.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female03.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female04.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female05.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female06.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female07.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female08.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female09.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female10.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female11.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female12.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female13.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female14.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female15.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female16.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female17.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female18.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female19.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female20.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female21.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female22.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female23.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female24.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female25.png'),
    ('FEMALE', 'https://storage.googleapis.com/withergate-images/avatars/female26.png');

-- Attribute templates
INSERT INTO attribute_templates (template_type, attr_sum, combat, scavenge, craftsmanship, intellect) VALUES
    ('BALANCED', 17, 5, 4, 4, 4),
    ('BALANCED', 15, 4, 5, 3, 3),
    ('BALANCED', 13, 2, 3, 5, 3),
    ('BALANCED', 11, 3, 2, 1, 5),
    ('BALANCED', 9, 2, 2, 3, 2),
    ('ECONOMY', 17, 4, 5, 4, 4),
    ('ECONOMY', 15, 5, 3, 5, 2),
    ('ECONOMY', 13, 2, 3, 5, 3),
    ('ECONOMY', 11, 2, 4, 3, 2),
    ('ECONOMY', 9, 2, 3, 2, 2),
    ('SMART', 17, 4, 4, 4, 5),
    ('SMART', 15, 3, 4, 4, 4),
    ('SMART', 13, 4, 3, 1, 5),
    ('SMART', 11, 3, 3, 2, 3),
    ('SMART', 9, 2, 3, 2, 2),
    ('COMBAT', 17, 5, 5, 4, 3),
    ('COMBAT', 15, 5, 3, 5, 2),
    ('COMBAT', 13, 3, 3, 2, 5),
    ('COMBAT', 11, 2, 4, 4, 1),
    ('COMBAT', 9, 4, 1, 1, 3);

-- Notification bootstrap
INSERT INTO global_notification VALUES
    ('GLOBAL', false),
    ('INGAME', false);

INSERT INTO localized_texts (global_notification, lang, text) VALUES
    ('GLOBAL', 'en', ''),
    ('GLOBAL', 'cs', ''),
    ('INGAME', 'en', ''),
    ('INGAME', 'cs', '');