-- Building details
INSERT INTO building_details(identifier, cost, bonus_type, bonus_text, bonus, passive_bonus_type, passive_bonus, passive_bonus_text, image_url) VALUES
    ('SICK_BAY', 12, 'HEALING', 'detail.healing.building', 2, 'CRAFTING_CONSUMABLE', 0, null, 'https://storage.googleapis.com/withergate-images/buildings/sickbay.png'),
    ('GMO_FARM', 12, null, null, 0, 'FOOD_INCOME', 2, 'building.gmofarm.income', 'https://storage.googleapis.com/withergate-images/buildings/gmofarm.png'),
    ('TRAINING_GROUNDS', 12, 'TRAINING', 'detail.building.training', 1, null, 0, null, 'https://storage.googleapis.com/withergate-images/buildings/traininggrounds.png'),
    ('MONUMENT', 16, null, null, 0, 'FAME_INCOME', 1, 'building.monument.income', 'https://storage.googleapis.com/withergate-images/buildings/monument.png'),
    ('FORGE', 12, null, null, 5, 'CRAFTING_WEAPON', 1, null, 'https://storage.googleapis.com/withergate-images/buildings/forge.png'),
    ('WORKSHOP', 12, null, null, 5, 'CRAFTING_GEAR', 1, null, 'https://storage.googleapis.com/withergate-images/buildings/workshop.png'),
    ('RAGS_SHOP', 12, null, null, 5, 'CRAFTING_OUTFIT', 1, null, 'https://storage.googleapis.com/withergate-images/buildings/ragsshop.png'),
    ('QUARTERS', 16, null, null, 0, 'POPULATION', 1, null, 'https://storage.googleapis.com/withergate-images/buildings/quarters.png'),
    ('STUDY', 16, 'RESEARCH', 'detail.building.study', 1, 'INFORMATION_INCOME', 1, 'building.study.income', 'https://storage.googleapis.com/withergate-images/buildings/study.png'),
    ('KENNELS', 12, null, null, 0, 'CLAN_DEFENSE', 2, null, 'https://storage.googleapis.com/withergate-images/buildings/kennels.png');

INSERT INTO localized_texts(building_name, lang, text) VALUES
    ('SICK_BAY', 'en', 'Sick bay'),
    ('SICK_BAY', 'cs', 'Marodka'),
    ('GMO_FARM', 'en', 'GMO farm'),
    ('GMO_FARM', 'cs', 'GMO farma'),
    ('TRAINING_GROUNDS', 'en', 'Training grounds'),
    ('TRAINING_GROUNDS', 'cs', 'Cvičiště'),
    ('MONUMENT', 'en', 'Monument'),
    ('MONUMENT', 'cs', 'Monument'),
    ('FORGE', 'en', 'Forge'),
    ('FORGE', 'cs', 'Kovárna'),
    ('WORKSHOP', 'en', 'Workshop'),
    ('WORKSHOP', 'cs', 'Dílna'),
    ('RAGS_SHOP', 'en', 'Rags shop'),
    ('RAGS_SHOP', 'cs', 'Hadrárna'),
    ('QUARTERS', 'en', 'Quarters'),
    ('QUARTERS', 'cs', 'Ubikace'),
    ('STUDY', 'en', 'Study'),
    ('STUDY', 'cs', 'Studovna'),
    ('KENNELS', 'en', 'Dog kennels'),
    ('KENNELS', 'cs', 'Psí kotce');

INSERT INTO localized_texts(building_description, lang, text) VALUES
    ('SICK_BAY', 'en', 'Feeling under the weather? Grab a bed and pull yourself together!'),
    ('SICK_BAY', 'cs', 'Je vám pod psa? Pojďte se u nás natáhnout!'),
    ('GMO_FARM', 'en', 'We finally realized how to genetically modify our animals without them growing a third head!'),
    ('GMO_FARM', 'cs', 'Teď už víme, jak těch našich pár zvířat geneticky vylepšit, aniž by jim narostla třetí hlava!'),
    ('TRAINING_GROUNDS', 'en', 'There is nothing we cant learn!'),
    ('TRAINING_GROUNDS', 'cs', 'Není nic, co by se tvůj velkolepý klan nemohl naučit!'),
    ('MONUMENT', 'en', 'Let everybody know the glory of your mighty clan by building a monument near your campsite!'),
    ('MONUMENT', 'cs', 'Ať všichni vidí, jak je náš klan úžasný!'),
    ('FORGE', 'en', 'Got some junk? Let`s forge some weapons for the arena!'),
    ('FORGE', 'cs', 'Roztavíme všechno. A slijeme z toho něco do arény!'),
    ('WORKSHOP', 'en', 'Great way how to turn junk into different type of junk.'),
    ('WORKSHOP', 'cs', 'Skvělý způsob, jak ze šrotu vyrobit jiný typ šrotu.'),
    ('RAGS_SHOP', 'en', 'We will make you a great outfit out of everything you found in the wasteland.'),
    ('RAGS_SHOP', 'cs', 'Uděláme ti skvělý vohoz ze všeho, cos našel v pustině.'),
    ('QUARTERS', 'en', 'No place to put your head down? We have a room for you! Dont mind the roaches.'),
    ('QUARTERS', 'cs', 'Nemáš, kde složit hlavu? Máme pro tebe fajnovej pokoj. Pokud ti teda nevadí pár švábů.'),
    ('STUDY', 'en', 'I have 100 ideas every day. 99 of them are bad and the remaining one is brilliant. The problem is finding which one is that.'),
    ('STUDY', 'cs', 'Každý den mám 100 nápadů. 99 stojí za prd a ten zbývající bývá geniální. Problém je zjistit, který z nich to je.'),
    ('KENNELS', 'en', 'This is Hutch. Hutch likes to cuddle, aport and shred. Hutch is a good boy.'),
    ('KENNELS', 'cs', 'Tohle je Alík. Alík se rád mazlí, aportuje a trhá.');

INSERT INTO localized_texts(building_info, lang, text) VALUES
    ('SICK_BAY', 'en', 'Each level of this building increases the hitpoints healed when resting. Sick Bay also enables you to craft medical items.'),
    ('SICK_BAY', 'cs', 'Každá úroveň této budovy zvyšuje počet vyléčených životů postav, které odpočívají. Kromě toho Marodka odemyká možnost výroby léčivých předmětů.'),
    ('GMO_FARM', 'en', 'Each level of this building grants free food every turn.'),
    ('GMO_FARM', 'cs', 'Každá úroveň této budovy poskytuje jídlo zdarma každé kolo.'),
    ('TRAINING_GROUNDS', 'en', 'Each level of this building grants free experience to all resting characters every turn. Additionally, increasing the level of this building increases the number of traits available for training for each character.'),
    ('TRAINING_GROUNDS', 'cs', 'Odpočívající postavy dostanou každé kolo zkušenosti zdarma. Kromě toho, zvyšování úrovně této budovy rošiřuje nabídku schopností k trénování pro každou postavu.'),
    ('MONUMENT', 'en', 'Each level of this building grants free fame every turn.'),
    ('MONUMENT', 'cs', 'Každá úroveň této budovy poskytuje slávu každé kolo.'),
    ('FORGE', 'en', 'This building grants the ability to craft weapons. Higher building levels unlocks more weapons to craft.'),
    ('FORGE', 'cs', 'Tato budova umožňuje vyrábět zbraně. Vyšší úroveň budovy odemyká více typů předmětů k výrobě.'),
    ('WORKSHOP', 'en', 'This building grants the ability to craft gear. Higher building levels unlocks more gear types to craft.'),
    ('WORKSHOP', 'cs', 'Tato budova umožňuje vyrábět vybavení. Vyšší úroveň budovy odemyká více typů předmětů k výrobě.'),
    ('RAGS_SHOP', 'en', 'This building grants the ability to craft outfits. Higher building levels unlocks more outfits to craft.'),
    ('RAGS_SHOP', 'cs', 'Tato budova umožňuje vyrábět zbroje. Vyšší úroveň budovy odemyká více typů zbrojí k výrobě.'),
    ('QUARTERS', 'en', 'Each level of this building increases your population limit.'),
    ('QUARTERS', 'cs', 'Každá úroveň této budovy navyšuje tvůj populační limit.'),
    ('STUDY', 'en', 'Each level of this building increases the speed of research and grants free information point every turn..'),
    ('STUDY', 'cs', 'Každá úroveň této budovy zvýší rychlost výzkumu a poskytuje informaci zdarma každé kolo.'),
    ('KENNELS', 'en', 'Each level of this building increases your clan defense against attacks from other players.'),
    ('KENNELS', 'cs', 'Každá úroveň této budovy zvyšuje obranyschopnost tvého klanu proti útokům od ostatních hráčů.');
