-- Building details
INSERT INTO building_details(identifier, cost, visitable, visit_junk_cost, image_url) VALUES
    ('SICK_BAY', 12, false, 0, 'https://storage.googleapis.com/withergate-images/buildings/sickbay.png'),
    ('GMO_FARM', 12, false, 0, 'https://storage.googleapis.com/withergate-images/buildings/gmofarm.png'),
    ('TRAINING_GROUNDS', 12, 0, false, 'https://storage.googleapis.com/withergate-images/buildings/traininggrounds.png'),
    ('MONUMENT', 16, false, 0, 'https://storage.googleapis.com/withergate-images/buildings/monument.png'),
    ('FORGE', 12, true, 10, 'https://storage.googleapis.com/withergate-images/buildings/forge.png'),
    ('WORKSHOP', 12, true, 10, 'https://storage.googleapis.com/withergate-images/buildings/workshop.png'),
    ('RAGS_SHOP', 12, true, 10, 'https://storage.googleapis.com/withergate-images/buildings/ragsshop.png'),
    ('QUARTERS', 16, false, 0, 'https://storage.googleapis.com/withergate-images/buildings/quarters.png'),
    ('STUDY', 16, false, 0, 'https://storage.googleapis.com/withergate-images/buildings/study.png');

INSERT INTO localized_texts(building_name, lang, text) VALUES
    ('SICK_BAY', 'en', 'Sick bay'),
    ('SICK_BAY', 'cs', 'Marodka'),
    ('GMO_FARM', 'en', 'GMO farm'),
    ('GMO_FARM', 'cs', 'GMO farma'),
    ('TRAINING_GROUNDS', 'en', 'Training grounds'),
    ('TRAINING_GROUNDS', 'cs', 'Cvičiště'),
    ('MONUMENT', 'en', 'Monument'),
    ('MONUMENT', 'cs', 'Monument'),
    ('FORGE', 'en', 'Forge'),
    ('FORGE', 'cs', 'Kovárna'),
    ('WORKSHOP', 'en', 'Workshop'),
    ('WORKSHOP', 'cs', 'Dílna'),
    ('RAGS_SHOP', 'en', 'Rags shop'),
    ('RAGS_SHOP', 'cs', 'Hadrárna'),
    ('QUARTERS', 'en', 'Quarters'),
    ('QUARTERS', 'cs', 'Ubikace'),
    ('STUDY', 'en', 'Study'),
    ('STUDY', 'cs', 'Studovna');

INSERT INTO localized_texts(building_description, lang, text) VALUES
    ('SICK_BAY', 'en', 'Feeling under the weather? Grab a bed and pull yourself together!'),
    ('SICK_BAY', 'cs', 'Je vám pod psa? Pojďte se u nás natáhnout!'),
    ('GMO_FARM', 'en', 'We finally realized how to genetically modify our animals without them growing a third head!'),
    ('GMO_FARM', 'cs', 'Teď už víme, jak těch našich pár zvířat geneticky vylepšit, aniž by jim narostla třetí hlava!'),
    ('TRAINING_GROUNDS', 'en', 'There is nothing we cant learn!'),
    ('TRAINING_GROUNDS', 'cs', 'Není nic, co by se tvůj velkolepý klan nemohl naučit!'),
    ('MONUMENT', 'en', 'Let everybody know the glory of your mighty clan by building a monument near your campsite!'),
    ('MONUMENT', 'cs', 'Ať všichni vidí, jak je náš klan úžasný!'),
    ('FORGE', 'en', 'Got some junk? Let`s forge some weapons for the arena!'),
    ('FORGE', 'cs', 'Roztavíme všechno. A slijeme z toho něco do arény!'),
    ('WORKSHOP', 'en', 'Great way how to turn junk into different type of junk.'),
    ('WORKSHOP', 'cs', 'Skvělý způsob, jak ze šrotu vyrobit jiný typ šrotu.'),
    ('RAGS_SHOP', 'en', 'We will make you a great outfit out of everything you found in the wasteland.'),
    ('RAGS_SHOP', 'cs', 'Uděláme ti skvělý vohoz ze všeho, cos našel v pustině.'),
    ('QUARTERS', 'en', 'No place to put your head down? We have a room for you! Dont mind the roaches.'),
    ('QUARTERS', 'cs', 'Nemáš, kde složit hlavu? Máme pro tebe fajnovej pokoj. Pokud ti teda nevadí pár švábů.'),
    ('STUDY', 'en', 'I have 100 ideas every day. 99 of them are bad and the remaining one is brilliant. The problem is finding which one is that.'),
    ('STUDY', 'cs', 'Každý den mám 100 nápadů. 99 stojí za prd a ten zbývající bývá geniální. Problém je zjistit, který z nich to je.');

INSERT INTO localized_texts(building_info, lang, text) VALUES
    ('SICK_BAY', 'en', 'Each level of this building increases the hitpoints healed when resting.'),
    ('SICK_BAY', 'cs', 'Každá úroveň této budovy zvyšuje počet vyléčených životů postav, které odpočívají.'),
    ('GMO_FARM', 'en', 'Each level of this building grants free food every turn.'),
    ('GMO_FARM', 'cs', 'Každá úroveň této budovy poskytuje jídlo zdarma každé kolo.'),
    ('TRAINING_GROUNDS', 'en', 'Each level of this building grants free experience to all resting characters every turn. Additionally, increasing the level of this building increases the number of traits available for training for each character.'),
    ('TRAINING_GROUNDS', 'cs', 'Odpočívající postavy dostanou každé kolo zkušenosti zdarma. Kromě toho, zvyšování úrovně této budovy rošiřuje nabídku schopností k trénování pro každou postavu.'),
    ('MONUMENT', 'en', 'Each level of this building grants free fame every turn.'),
    ('MONUMENT', 'cs', 'Každá úroveň této budovy poskytuje slávu každé kolo.'),
    ('FORGE', 'en', 'Pay junk and craft a random weapon! High craftsmanship and building level affect the rarity of the crafted item. Higher building levels decrease the crafting cost.'),
    ('FORGE', 'cs', 'Zaplať šrot a vyrob náhodnou zbraň! Zručnost a úroveň budovy ovlivňují šanci na vyšší raritu předmětu. Vyšší úroveň budovy navíc snižuje cenu výroby.'),
    ('WORKSHOP', 'en', 'Pay junk and craft a random gear! High craftsmanship and building level affect the rarity of the crafted item. Higher building levels decrease the crafting cost.'),
    ('WORKSHOP', 'cs', 'Zaplať šrot a vyrob náhodný kus výbavy! Zručnost a úroveň budovy ovlivňují šanci na vyšší raritu předmětu. Vyšší úroveň budovy navíc snižuje cenu výroby.'),
    ('RAGS_SHOP', 'en', 'Pay junk and craft a random outfit! High craftsmanship and building level affect the rarity of the crafted item. Higher building levels decrease the crafting cost.'),
    ('RAGS_SHOP', 'cs', 'Zaplať šrot a vyrob náhodný oděv! Zručnost a úroveň budovy ovlivňuj šanci na vyšší raritu předmětu. Vyšší úroveň budovy navíc snižuje cenu výroby.'),
    ('QUARTERS', 'en', 'Each level of this building increases your population limit.'),
    ('QUARTERS', 'cs', 'Každá úroveň této budovy navyšuje tvůj populační limit.'),
    ('STUDY', 'en', 'Each level of this building increases the speed of research and grants free information point every turn..'),
    ('STUDY', 'cs', 'Každá úroveň této budovy zvýší rychlost výzkumu a poskytuje informaci zdarma každé kolo.');
