package com.withergate.api.model;

/**
 * BonusType enum.
 *
 * @author Martin Myslik
 */
public enum BonusType {

    CRAFTING, CONSTRUCT, SCAVENGE_FOOD, SCAVENGE_JUNK, RESEARCH, SCOUTING, FACTION_POINTS,
    COMBAT_MELEE, COMBAT_RANGED, COMBAT_UNARMED, FOOD_CONSUMPTION, HEALING, DISASTER, CAMOUFLAGE, TRAINING

}
